apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgis-example-deployment
  labels:
    app: postgis-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgis-example
  template:
    metadata:
      labels:
        app: postgis-example
    spec:
      containers:
        - name: postgis-example
          imagePullPolicy: Never
          image: example/postgis:2
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: postgis-example
  labels:
    app: postgis-example
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: postgis-example
